### ISSUE TITLE
fix bin/encrypt_for_travis.sh to not recreate all of share/travis_secrets

### ISSUE THREAD

**Issue by igalic** [voxpupuli/plumbing#10]
currently, when we issue a new secret, we do so by "simply" recreating all secrets from based on `share/modules`.

two big disadvantages is that this process is terribly slow, and the diff isn't unintelligible.

**Comment by nibalizer** [comment]
Probably should fix this in part by making share/modules and share/travis_secrets both .yaml files

**Comment by ekohl** [comment]
Now that we've dropped Travis secrets, this has been solved.
