### ISSUE TITLE
Elevate me to 'administrator'

### ISSUE THREAD

**Issue by roidelapluie** [voxpupuli/plumbing#109]
Giving me admin rights to the VP organisation will enable my work as Security Officer.

Here is a small list of tasks that require those rights:

- Revoking compromised user account
- Accessing the security logs
- Pushing to all repositories, reverting malicious commits
- ...

**Comment by bbriggs** [comment]
+1

**Comment by nibalizer** [comment]
Let's do it

**Comment by roidelapluie** [comment]
Thanks!
