### ISSUE TITLE
Transferring https://github.com/erwbgy/puppet-system to voxpupuli

### ISSUE THREAD

**Issue by damnski** [voxpupuli/plumbing#135]
Hi, 

I've been working with rnelson0 and Keith Burdis to transfer https://github.com/erwbgy/puppet-system to voxpupili.  Keith Burdis has agreed to migrate and should be transferring the repo soon.  Rob asked me to create this issue on this repo for tracking.

Best,
-dkw
Darryl

**Comment by bastelfreak** [comment]
Hi,
I sent out github invitations to @damnski and @erwbgy.

**Comment by erwbgy** [comment]
puppet-system currently has:

dependency 'erwbgy/limits', '>= 0.3.1'
dependency 'erwbgy/ntp', '>= 0.7.1'

Ok for me to transfer those as well?

Are any of the other modules at https://forge.puppet.com/erwbgy of interest?

**Comment by oranenj** [comment]
Perhaps it would be a better idea to adapt the module to depend on already maintained modules? eg. puppetlabs/ntp and saz/limits (maybe)?

**Comment by erwbgy** [comment]
Fine by me either way, though erwbgy/limits seems pretty popular on Puppet
Forge.

**Comment by juniorsysadmin** [comment]
Any tasks remaining for this?

**Comment by bastelfreak** [comment]
Stuff that needs to happen:
* release puppet-system
* mark the old module as deprecated

**Comment by bastelfreak** [comment]
@erwbgy the ntp module should probably me deprecated in favour of puppetlabs-ntp. A search for 'limits' makes me a bit sad: https://forge.puppet.com/modules?utf-8=%E2%9C%93&sort=rank&q=limits

Would be awesome if the ones form saz and puppetlabs got merged....

**Comment by bastelfreak** [comment]
* Released puppet-system
* opened https://tickets.puppetlabs.com/browse/MODULES-5736
