### ISSUE TITLE
puppet-gitlab migration

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/plumbing#160]
- [x] @tobru added to the modules/admin team
- [x] Repository transferred
- [x] Github issues enabled
- [x] Verify that all webhooks except travis are disabled
- [x] Update the README.md with a description of the deprecation and a link to the new module location - to be done by @tobru 
- [x] Release a copy of your module to the ‘puppet’ forge account - to be done by @tobru 
- [x] Add the module to our modulesync setup
- [x] Add the module to our plumbing repository(handles travis secrets)
- [x] Ask one of the admins to add the module to the collaborators Team on Github.
- [x] Execute modulesync for this module
- [x] Create a Jira issue at https://tickets.puppetlabs.com and ask to deprecate the old module (and approve the new one if the old one was approved as well)

**Comment by juniorsysadmin** [comment]
- [ ] Sync labels

**Comment by tobru** [comment]
Thanks @juniorsysadmin for taking care of this!! 🥇

**Comment by tobru** [comment]
* Updated README with deprecation link: https://github.com/voxpupuli/puppet-gitlab/commit/d349659df6d357e14bcbca646306dc7483f6798c
* Configured travis secret: https://github.com/voxpupuli/puppet-gitlab/commit/f97971b0898d05b7309155aa480f9cde23d54bc2

**Comment by tobru** [comment]
@juniorsysadmin I would be very happy if you could help me to get a release out soon. It's about time to finish the migration of the module to Vox Pupuli. What else is needed from my side?

**Comment by tobru** [comment]
Release PR: https://github.com/voxpupuli/puppet-gitlab/pull/190

**Comment by tobru** [comment]
Finally: https://forge.puppet.com/puppet/gitlab

**Comment by tobru** [comment]
Ticket in Puppet JIRA: https://tickets.puppetlabs.com/browse/MODULES-6610

**Comment by hunner** [comment]
On Wed, Feb 7, 2018 at 11:58 AM, Tobias Brunner <notifications@github.com>
wrote:

> Ticket in Puppet JIRA: https://tickets.puppetlabs.com/browse/MODULES-6610
>

Thanks! I've added the deprecation notice and moved the approved label to
VPs.

**Comment by dhollinger** [comment]
I think this can be closed now.

I'll defer to @tobru

**Comment by tobru** [comment]
Thanks for taking care. I consider this now finally done 🎉
