### ISSUE TITLE
puppet-python migration

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/plumbing#167]
- [ ] @stankevich   added to the modules/admin team
- [x] Repository transferred
- [x] Github issues enabled
- [x] Verify that all webhooks except travis are disabled
- [x] Update the README.md with a description of the deprecation and a link to the new module location - to be done by @stankevich   
- [ ] Release a copy of your module to the ‘puppet’ forge account - to be done by @stankevich   
- [x] Add the module to our modulesync setup
- [x] Add the module to our plumbing repository(handles travis secrets)
- [ ] Ask an admin to add the collaborators team to the module’s Collaborators & Teams ‘Teams’ list with Write permissions
- [x] Execute modulesync for this module
- [ ] Create a Jira issue at https://tickets.puppetlabs.com and ask to deprecate the old module (and approve the new one if the old one was approved as well)
- [x] Sync labels

**Comment by ekohl** [comment]
It looks like this was fully migrated and I'm going to close this.
