### ISSUE TITLE
use vault for storing credentials

### ISSUE THREAD

**Issue by igalic** [voxpupuli/plumbing#17]
we should use vault for storing our forge credentials

@daenney offered to write a small service for retrieving a travis secret from the vault
so *anyone* could use it to update their secret.

**Comment by daenney** [comment]
Yes. So the idea is we have a vault with our keyspace for puppet-community (or $name). We'll have keys in there like forge_password etc. for which we can hand out a read-only key to every module that joins us which in turn can be encrypted by `travis encrypt` and stored there.

The owners of the org will also have a key that gives them write access to the secret so we can update it when needed without anyone else needing to know about the change of credential.

**Comment by nibalizer** [comment]
That doesn't make any sense to me. 

1) We only have one password for the puppet forge, all modules share the same password. 
2) An encrypted file in a git repo is infinitely simpler than a secret service.
3) Assuming we're talking about hashicorp vault, that was never intended to be run on the public internet.

**Comment by daenney** [comment]
1. That might not be true in the future
2. As long as we rely on PGP for it, no it is not
3. I wasn't specifically talking about Vault the product, there's a few that implement a similar paradigm

**Comment by nibalizer** [comment]
PGP isn't that hard. It's not great for encrypting emails. It's actually really good at having a secret password encrypted to N individuals.

**Comment by nibalizer** [comment]
We already run pcci, so maybe the way forward is to remove travis from the release pipeline all together, run our own release pipeline on servers we control and inject credentials that way.

**Comment by daenney** [comment]
Yeah, I've actually been thinking the same. I'm curious if we couldn't just spin up a Drone CI instance ourselves without much trouble. Or a Go (the thing by Thoughtworks). And see if we can get the Beaker testing in there too by leveraging Docker. They've done some recent work allowing you to run Beaker "as is", so without it needing to orchestrate remote machines.

**Comment by nibalizer** [comment]
Whatever problems GPG has around being hard to use, git is far, far worse.

**Comment by daenney** [comment]
Anecdotal evidence between the amount of people that manage to use git every day vs GPG invalidates that statement :stuck_out_tongue:.

**Comment by igalic** [comment]
sick :fire:

**Comment by daenney** [comment]
I'm going to close this one for now, I think we need to revisit it once we have hammered out our different processes a bit more. I'm hoping that when we do so we'll be able to consolidate the services that need credentials to very few instead of every module so this issue will be moot.
