### ISSUE TITLE
sync labels between on our org

### ISSUE THREAD

**Issue by igalic** [voxpupuli/plumbing#18]
we should create a script(?) to sync labels and other settings between repositories on our org.

**Comment by juniorsysadmin** [comment]
Yes. Do you have a proposed list of labels?

**Comment by igalic** [comment]
@juniorsysadmin i think the one from nodejs is pretty complete
i also think that @underscorgan's community tools should be able to help us out here: https://github.com/underscorgan/community_management

**Comment by juniorsysadmin** [comment]
I've updated the labels for nodejs . Added question, beginner friendly, needs-squash, needs-help and won't fix . Renamed feature to enhancement
Colors same as for the puppetlabs namespace, except for the ones that I added.

Note that labels need to be able to apply to both issues and PRs.

Okay to roll this out everywhere?

**Comment by igalic** [comment]
:+1:

**Comment by juniorsysadmin** [comment]
Got rid of invalid label as well. Labels have been synced for all modules in managed_modules.yml in modulesync_config

**Comment by juniorsysadmin** [comment]
See https://github.com/voxpupuli/plumbing/pull/40 for label setup and how to sync
