### ISSUE TITLE
RFC: Support Puppet 4 only

### ISSUE THREAD

**Issue by daenney** [voxpupuli/plumbing#21]
# RFC: Support Puppet 4 only

This is going to be a bit controversial because I'm raising it this early. This is not a proposal to move to Puppet 4 only now now now. Instead it is meant for us to find a good way on how to move to Puppet 4 and define some metrics at which point we deem it acceptable to move to a Puppet 4 only version of our modules.
## Reasons for moving to Puppet 4

Puppet 4 brings a vast number of improvements but besides the runtime speedup it's mostly language features and sanitisation that we, the developers, can benefit from allowing us to write more concise, bug-free, testable and compact manifests. This in turn raises the quality of our modules which is good for everyone that uses them. Some of the features deemed most important:
- the type system (and thus being able to avoid all the `validate_*` and `is_*` functions) which gets us decent error reporting for free
- native iteration avoiding the need for all kinds of "creative" iteration hacks (and therefor no more `create_resources` too)
- the protected, read-only, `$facts` hash (instead of all the `$::fact`s) which will [facilitate migrating to a `strict_variables` enabled future](https://github.com/rodjek/rspec-puppet/issues/344)

Additionally a new way to deal with data in modules is starting to emerge in Puppet 4 that in due time we'll be able to take advantage of too (though perhaps not before Puppet 5 depending on when the feature is deemed finalised).
## Collecting data

The most important thing to do in order to decide when the time is right is to collect as much data as we can on Puppet 4 deployments and their ratio to Puppet 3.

Data that could help us make this decision:
- Internal survey with Vox Pupuli members to figure out how far along our "avant-garde" is
- Public survey (join forces with Puppet Labs) to get some deployment figures on Puppet 4 (perhaps every half year?)
- Download statistics from the official tarballs and repositories, both FOSS and PE
- Download statistics from the Forge (if they can tell us anything wrt Puppet 4 deployment)
## When to move

The problem with all of this is once we move to Puppet 4 only the code will simply not work anymore on older versions of Puppet, most notably Puppet 3 which is still widely deployed. Though Puppet 4 has been out for a year now and multiple community members are holding talks at PuppetConf, Puppet Camp's and Configuration Management Camp on how to migrate to Puppet 4 and what new features it brings adoption is still slow. Puppet Labs has successfully been pushing Puppet 4 through PE upgrades.

As such we need to define a threshold at which point, based on the data that we decide to collect, we believe the time is right to move to Puppet 4. However, when we do decide to do so we should still provide critical bug fix releases for Puppet 3 compatible versions of our modules for a number of months to not unnecessarily complicate other people's lives.

Therefor I would propose a transition somewhere along these lines:
- An announcement goes out through all our channels a month before this change goes into effect to give everyone some time to prepare (pin version requirements etc.)
- A Puppet 3 release of the module must be available which is "perfect", i.e it doesn't generate deprecation warnings or other problems when run on the latest version of Puppet 3 with and without the future parser enabled
- A major version release for every module needs to happen (preferably paired with some validation cleanup by leveraging the type system instead) and accordingly reflected in `metadata.json`
  - **_suggestion**_: We should try and keep other module changes to a minimum during that upgrade. Though a major version upgrade would be traditionally where we change the API it's going to be hard enough with the language transition already that we shouldn't add too much baggage.
- For a period of 3-6 months, at the discretion of the module maintainers, bug fixes and releases for Puppet 3 compatible versions of the module will still be made but no new features will be accepted

The one question that remains: **how do we decide it is time?**
## List of tasks / bugs that we need to do/fix prior to being able to move
- [ ] Puppet 4 (future parser) style guide
### puppet module tool
- [ ] [PUP-5688: respect version constraint in `metadata.json`](https://tickets.puppetlabs.com/browse/PUP-5688)
- [ ] [PUP-5689: allow specifying the version of the module that should be installed](https://tickets.puppetlabs.com/browse/PUP-5689)
### rspec-puppet
- [ ] https://github.com/rodjek/rspec-puppet/issues/344
### puppet-lint
- [ ] https://github.com/rodjek/puppet-lint/issues/451
- [ ] https://github.com/rodjek/puppet-lint/issues/450
- [ ] https://github.com/rodjek/puppet-lint/issues/456

**Comment by electrical** [comment]
I've been asking my self this question as well for a while.
The only decision I've made so far that the next major version of my modules ( 2.x ) will support puppet 4.x only.
This does mean that i have to maintain 2 branches of the module and port changes back and forth.
But the idea im playing with now is that when i release 2.0.0 that 1.x will be in maintenance mode.

**Comment by roidelapluie** [comment]
It will be time when there will be a decent linting/style guide for the new puppet 4 features, otherwise that will be horrible.

**Comment by daenney** [comment]
> It will be time when there will be a decent linting/style guide for the new puppet 4 features, otherwise that will be horrible.

That's a very good point. Having a functional style guide will be important to avoid all kinds of unnecessary discussion on this topic.

**Comment by roidelapluie** [comment]
Should we make a Puppet-4-Style-Guide repo ?

**Comment by daenney** [comment]
It's a thought though I would suggest we post the question to puppet-dev@ first. There might already be things in the work and it would be a shame to duplicate such efforts.

**Comment by danzilio** [comment]
I wish PMT could actually consume the metadata in modules, i.e. installing only compatible versions. Maybe we should contribute this feature?

**Comment by daenney** [comment]
> I wish PMT could actually consume the metadata in modules, i.e. installing only compatible versions. Maybe we should contribute this feature?

That's almost impossible to do. The master can be on a much newer version than the agent and even have modules in its environment that don't work with specific distros that the agents can be running on. The only place you could reliably do it is in a masterless environment because there you only have to care about the local machine.

**Comment by danzilio** [comment]
> That's almost impossible to do.

grumble grumble reality grumble grumble

**Comment by daenney** [comment]
Alright, total aside here and stop derailing my RFCs already @danzilio but:

If there was some way of declaring API compatibility, like API levels in Android, the agents could do this work.

Consider a module which declares that it will only work with Language level 4 and is determined to be part of the catalog that an agent needs to apply which only supports up to Language Level 3. There's nothing to stop us from halting execution right then. Similarly we can probably have the agent check the module constraints, so that it doesn't try to run on a too old version of the agent or a platform that's not supported (potentially with a flag to override that if you're on one of those weird distros that usually works but no one bothers to check for).

I think what you're suggesting is actually quite feasible, just not by leveraging the PMT.

**Comment by danzilio** [comment]
@daenney keeps taking the bait ;)

**Comment by ahpook** [comment]
> [PMT consuming module metadata is] almost impossible to do. The master can be on a much newer version than the agent and even have modules in its environment that don't work with specific distros that the agents can be running on. The only place you could reliably do it is in a masterless environment because there you only have to care about the local machine.

I suppose that's true, but given an agent/master workflow where you use PMT on the master to download modules, the majority case is that your agents are not going to cross major-version boundaries. One concrete improvement to PMT that might help a lot would be adding the ability to fall back to other versions if the latest/current one expresses incompatibility with the version of puppet. (Or hell, even just display what other versions are available)

**Comment by ahpook** [comment]
One meta comment @daenney: is the scope of this discussion about the contents of this repo? Or more broadly about stuff inside the vox pupuli namespace?

**Comment by daenney** [comment]
@ahpook The latter, the contents of this repo are irrelevant. We use the "plumbing" repository for things w.r.t to how work/function, the "plumbing" of our community/project.

**Comment by nibalizer** [comment]
We had a similar conversation on the dotnet module: https://github.com/voxpupuli/puppet-dotnet/pull/9

**Comment by nibalizer** [comment]
Oh man can fixing the PMT not be part of scope here?

**Comment by daenney** [comment]
> Oh man can fixing the PMT not be part of scope here?

Completely agree. Part of a different discussion. This is part of "how do we decide when it's time to move and how do we go about it".

**Comment by nibalizer** [comment]
@daenney I disagree that we should drop puppet3 support before enabling puppet4 support. I think we need to have branches.

I think every module should have a table like this in the readme:
https://github.com/puppetlabs/puppetlabs-stdlib#version-compatibility

If we hard cut modules to puppet4 at some arbitrary date, we'll just grow uncontrolled forks of people patching the last puppet3 version. If we keep a puppet3 branch around for a couple years, then people who haven't upgraded yet have a place to collaborate.

Creating a puppet4 branch (or moving master to puppet4) enables people to start using puppet4 and will help drive puppet4 adoption. We should do that sooner rather than later.

**Comment by daenney** [comment]
> If we hard cut modules to puppet4 at some arbitrary date, we'll just grow uncontrolled forks of people patching the last puppet3 version.

I never proposed just yoloing it on some arbitrary date. I set very specific data sources that I would like to poll to get a feel at which point we can make this switch and a period in which we should continue to maintain this.

> If we keep a puppet3 branch around for a couple years, then people who haven't upgraded yet have a place to collaborate.

That's a good idea.

> Creating a puppet4 branch (or moving master to puppet4) enables people to start using puppet4 and will help drive puppet4 adoption. We should do that sooner rather than later.

Not unreasonable. But then we need to iron out a few things like how do we deal with a potentially diverging feature set.

**Comment by ahpook** [comment]
Sure, sorry to derail it @nibalizer.

I totally think the stdlib model is a workable one - major versions to express breaking compatibility with older puppet major versions.  Keep a branch per major in the main repo. For the Puppet projects, we put new features only in the latest major branch but backport bugfixes as long as it's not super invasive, but YMMV.  

The tooling ecosystem problem is a big one. Is there a hit-list of things needed for puppet-lint and rspec to fully work on Puppet 4?

**Comment by daenney** [comment]
Nope, but that's a great idea. I've added a few now.

**Comment by roidelapluie** [comment]
What should we do for the forge?

I think if we use branch we should also publish on the forge under different names?

puppet-corosync and puppet-corosync4 ?

**Comment by danzilio** [comment]
:sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by electrical** [comment]
@roidelapluie Why not just have a major version bump which is then puppet 4 ready? like have version 1.x for puppet 3.x and 2.x for puppet 4.x ?

**Comment by roidelapluie** [comment]
Because users rely on the Forge API "current_release" ? is PMT able to retrieve the latest release that is available for your puppet version?

**Comment by daenney** [comment]
That's going to cause major confusion. Is puppet-corosync4 version 4 of the module, compatible with version 4 of corosync, compatible with Puppet 4?

This should be fixed in the PMT, it should simply be possible to instruct it which version you want fetched just like r10k and librarian-puppet can and coincidentally respect the Puppet version constraint.

**Comment by roidelapluie** [comment]
ok makes sense

**Comment by ahpook** [comment]
> This should be fixed in the PMT, it should simply be possible to instruct it which version you want fetched just like r10k and librarian-puppet can and/or respect the Puppet version constraint.

I think that's what I suggested last week :)

**Comment by daenney** [comment]
@ahpook I just added two issues for you related to the PMT ;).

**Comment by jyaworski** [comment]
So we're going to maintain two versions of puppet for our modules? That's a tall order. I would say we start with more puppet4 testing. For example, adding 4.3.1 to the test matrix in modulesync and making sure it at least runs. We can worry about porting all the syntactic sugar later.

**Comment by daenney** [comment]
> So we're going to maintain two versions of puppet for our modules? That's a tall order.

Where did you get that from? So far, these are proposals. No road has been taken or any decision made.

**Comment by jyaworski** [comment]
Right; it was mainly a straw-man taken from some of the earlier comments. Let me be clear with my proposal, then.

I propose we get our modules in such a state that they compile cleanly on puppet 3.8 and puppet 4. I'm fine with dropping support for <3.8.

**Comment by roidelapluie** [comment]
I'm fine with dropping support for <3.8 and (>= 4.0 <= 4.3)

**Comment by jyaworski** [comment]
So how about we drop our testing for <3.8, and add explicit testing for the latest stable versions of 4.x? 4.0, 4.1, etc.

**Comment by daenney** [comment]
4.0 and 4.1 of Puppet 4 are unusable and not compatible with 3.8 + future parser in a number of places. 4.2 is the lowest we can safely and sanely support. Everything you're suggesting however is already in place as we always pick the latest 3.0 release.

**Comment by jyaworski** [comment]
Again with the -> syntax. Ignore me. :)

Keep doing what we're doing. Maybe test 3.8 with both the current parser and the future parser, just to be pedantic?

**Comment by daenney** [comment]
That is probably a good idea. Feel free to send a PR to modulesync_config to add that one to the matrix.

**Comment by ahpook** [comment]
Hey all, resurrecting this. I would like to see us get to resolution on this so I can publish some docs on the front page of the Forge for all module authors who are interested in Puppet 4 support.  What do y'all think about this?


* Use semantic versioning for your module
* Create a VCS branch for your module's existing "major" series, and express Puppet compatibility with Puppet<=3.x, Puppet Enterprise<=3.x. This will allow you to continue maintenance releases on the current series, so your 3.x users are not abandoned
* Use your 'master' branch for Puppet 4-only development; express Puppet version compatibility with Puppet>=4.0, Puppet Enterprise>=2015.2. This will prevent the puppet module tool on older versions of Puppet from installing an incompatible version. You can then begin using iteration, the type system, etc without needing to support both parsers in one branch of code.

Caveats: 
* users who are on 3.x but using the future parser may technically be able to use your 4.x branch but the module tool will not permit downloading it (this is acceptable IMO as we want them upgrading!). 
* You will have to maintain two branches until you decide to drop 3.x support, but we have successfully used this model with puppetlabs-stdlib and it's not a bad way to go.

**Comment by roidelapluie** [comment]
Hi @ahpook 

What about the style guide/best practices? Does someone already bootstrap that effort? We really need something before pushing puppet 4 only code.

**Comment by daenney** [comment]
Do we really though? We did without a style guide on Puppet 0.x - 2.7 and yes it resulted in some unfortunate things but the style guide as it exists now is mostly a reflection of the best practices that came out of the community.

Just about all of it still applies to Puppet 4 too. The only major thing that needs some thinking is how to deal with long(ish) type annotations, especially on parameters.

**Comment by ahpook** [comment]
Good point @roidelapluie I am working on that as well - but note this is not specifically about using any new language features, just making code that might not work (or might work differently) on 3.x.

**Comment by roidelapluie** [comment]
@ahpook is there anything public ? How van we help?

**Comment by roidelapluie** [comment]
@daenney no, there are a lot of other stuff.

**Comment by daenney** [comment]
> @daenney no, there are a lot of other stuff.

How about some examples then of what you feel is lacking?

**Comment by roidelapluie** [comment]
* When to enforce type checking (semotimes a variable is type checked in the params, should you enforce it again in the «with» functions or not, etc)
* How deep should we type the variables?
* Should be allow the use of the any type
* good/bad use cases for the reduce function (e.g: do not create resources inside a reduce function)
* good bad usecase of splat array
* splat parameters: should be use
```puppet
class {
  'a':
    * => $a,
    * => $b,
}
```
or
```puppet
class {
  'a':
    * => $a + $b,
}
```

**Comment by hlindberg** [comment]
@roidelapluie It would be very good to start a shared google doc to collect all the stylistic issues; starting with asking all the questions (like you just did). I would like to see a much more comprehensive style guide than what has been available historically and that has a bit more nuance than just "do / don't". I am happy to help out working on that.

**Comment by hlindberg** [comment]
In Puppet 4.5.0 there will be a --strict flag (settable to off, warning, and error). Behind that flag there will be several added new validations intended as helping maintaining a sound code base. We have an epic in Jira called "Theme: Validation" from which you can navigate to "4.x Validation", "5. Validation". Validation related tickets are associated with those. Things we could do in puppet that you think are helpful in making it easier to transition to 4.x (in the validation domain) are very welcome.

**Comment by roidelapluie** [comment]
https://etherpad.openstack.org/p/Puppet_4_StyleGuide

**Comment by rnelson0** [comment]
We are approaching the EOL date for Puppet 3 now, just 4 months away. It appears that all of the outstanding issues are still outstanding. Are they all actually required to swing to P4 support only? I think the PMT ones specifically can be moved to a "Desired/Optional" section. Of the rest, I would like to address the puppet-lint tasks sometime between now and the end of the community summit/hack at PuppetConf and have put them all against the 2.1.0 milestone. The [style guide](https://docs.puppet.com/guides/style_guide.html) has been receiving regular updates and I believe is future parser compatible - and the future of puppet-lint is to line its checks up with the guide. That leaves the rspec-puppet issue, which I cannot speak to.

I do think that "once we move to Puppet 4 only the code will simply not work anymore on older versions of Puppet" is not fully accurate - we can support only Puppet 4 but much of the code will continue to work unsupported with Puppet 3, until actual changes are made that rely on P4 only constructs. Only the modules that are currently Puppet 4-only would not be backward compatible on Day 0 of the change. While that may (rapidly?) change, it eases the transition.

For a timeframe, I suggest that we announce our planned drop of Puppet 3 support by November 1st via the website, twitter, and the mailing list. By November 30, we ensure that all modules have an up to date release supporting P3. Starting on January 1, we update modules to remove the support for P3 (metadata, travis, anything else?) and release new MAJOR versions when the next fix/feature is implemented. We support P3 only for emergency fixes on the older branches through 4/30/2017, one third of the calendar year.

By announcing deadlines for ending P3 support and patching ahead of time, we can ensure that it's really difficult for anyone to be surprised by the change, and we do not need to rewrite all the modules top to bottom, either.

**Comment by daenney** [comment]
> For a timeframe, I suggest that we announce our planned drop of Puppet 3 support by November 1st via the website, twitter, and the mailing list. By November 30, we ensure that all modules have an up to date release supporting P3. Starting on January 1, we update modules to remove the support for P3 (metadata, travis, anything else?) and release new MAJOR versions when the next fix/feature is implemented.

From my experience, December and January are hectic enough with last-minute oh-no-vacation oh-shit-new-legislation god-damn-not-this-thing-too issues that we shouldn't compound that with Puppet module changes since it's so difficult for people to avoid upgrading across major version boundaries with the tools we currently have in your ecosystem (most notably PMT and nothing does any kind of Puppet compatibility checking even though the modules provide the necessary metadata).

**Comment by rnelson0** [comment]
When do you think would be a better time to make the cut?

**Comment by daenney** [comment]
I would suggest we keep your timeline with regards to adding the warnings etc. but only flip the bit in February so that everyone's had some time to catch their breath after new year.

**Comment by rnelson0** [comment]
Revised proposal (in the one true date format):

- [ ] 20161101 - Announce planned deprecation of Puppet 3 development effective 20170131 and Puppet 3 support effective 20170430, via website, mailing list, twitter, slack, irc, etc.
- [ ] 20161101-20161130 - Ensure all Vox Pupuli modules have a current release supporting Puppet 3.
- [ ] 20170101 - Public reminder of planned deprecation.
- [ ] 20170131 - Public announcement ending Puppet 3 development by Vox Pupuli. Support continues until 20170430.
- [ ] 20170201 - Start removing Puppet 3 metadata from modules, to be used on the next published version which would be a MAJOR version.
- [ ] 20170401 - Reminder of deprecation of Puppet 3 support effective 20170430.
- [ ] 20170430 - Announcement: end of all Puppet 3 development and support by Vox Pupuli.

**Comment by juniorsysadmin** [comment]
@rnelson0 Consider moving the end of date forward from 20170430 to 20170331 perhaps, otherwise sounds good to me.

**Comment by mmckinst** [comment]
I created a couple puppet linters to migrate facts to a newer style for puppet 4

* [top_scope_facts](https://github.com/mmckinst/puppet-lint-top_scope_facts-check) - lints for facts like `$::operatingsystem` and replaces them with `$facts['operatingsystem']` . The `$facts` hash is so much easier to read IMHO, using it should be added to the style guide once puppet 3 is gone. Even if you're on puppet 3 you should turn on `trusted_node_data` just to use the facts hash.
* [legacy_facts](https://github.com/mmckinst/puppet-lint-legacy_facts-check) - lints for so called legacy facts like `$facts['operatingsystemmajrelease']` or `$::operatingsystemmajrelease` and replaces them with the new fancy structured fact like `$facts['os']['release']['major']`

**Comment by daenney** [comment]
@mmckinst Nice! If they're not on our site yet, would you mind submitting a PR against voxpupuli/voxpupuli.github.io, w.r.t to https://github.com/voxpupuli/voxpupuli.github.io#puppet-plugins? Essentially updating this filehttps://github.com/voxpupuli/voxpupuli.github.io/blob/master/_data/tools/puppet-lint.json with your plugins.

**Comment by rnelson0** [comment]
I've engaged the PMC now that we have one to get the announcement out!

@juniorsysadmin I specified April so there was a 90 day window between deprecation and end of support. Do you think 60 days is sufficient? (sorry I missed the comment back in August)

**Comment by juniorsysadmin** [comment]
> Do you think 60 days is sufficient?

Yes

**Comment by bastelfreak** [comment]
Good evening everybody. The PMC has created a proposal for the Puppet 4 deprecation. We would like to discuss the following with you and make a decision in the next days via  lazy consensus.

---

# Deprecation of Puppet 3

## The End of Puppet 3

Puppet 3 will be End of Life [2016-12-31](https://rnelson0.com/2016/10/25/puppet-3-end-of-life-12312016/). We see Vox Pupuli as a vendor of many software products. As a vendor we are responsible for the security of our users and should not encourage them to use outdated or end-of-life software. Therefor we will start to deprecate Puppet3 at 2017-01-01.

## Timeline

* Now(): We will add a warning into each of our modules that warns you about our deprecation of Puppet3 after 2016-12-31.
* 2016-11-30: Official 30 day warning period begins. Every module will be released before this date including the mentioned warning.
* 2017-01-01: We will start the deprecation after now. Apply latest modulesync to our modules + release them with all outstanding commits. After that we do a major release which drops Puppet3 from metadata.json.
0Looking

**Comment by rnelson0** [comment]
I think we previously noted that we don't want to force people to come back from a holiday vacation and have to deal with upgrading the world right away. If we could give people at least 15-30 days before we start the new, puppet3-less releases, it may make for a better user experience.

Otherwise I do like the accelerated timelines if we get consensus.

**Comment by nibalizer** [comment]
Whoa I don't think adding a warn() function to every module is in any way polite. Someone could easily get a dozen or more warnings every puppet run.

**Comment by nibalizer** [comment]
To me, it seems like we only need to do two things on 2017-01-01
1) Create a 'puppet3' branch for every module
2) Write a blog post that says "Puppet 3 is dead, the Puppet 4 floodgates are open, write whatever you want!" 

Then whenever a module gets puppet4 only code, the next release of it bumps the major version.

I don't think we need to release every module just to add warnings.  I don't think we need to drop puppet3 from metadata.json unless puppet4 code was added.

**Comment by Cinderhaze** [comment]
@nibalizer - would adding a suppress_puppet3_deprecation_warning parameter that defaults to false on all modules be more polite? That would enable a consistent way via hiera's APL to disable the warnings?

**Comment by hlindberg** [comment]
> On 05 Nov 2016, at 09:35, Spencer Krum <notifications@github.com> wrote:
> 
> Whoa I don't think adding a warn() function to every module is in any way polite. Someone could easily get a dozen or more warnings every puppet run.
> 

There is a “warn_once” option for puppet deprecations that uses a symbol/string for the uniquness. Thus, if all vox populi modules uses the same warn_once symbol it is only shown once.

- henrik

**Comment by DavidS** [comment]
@nibalizer that's the way I chose to do the puppet3 deprecation for the NTP example module: 4.2.0 was the last release to support puppet 3, with the change to ntp v5.0 we "silently" dropped puppet 3 support and started using puppet 4 features.

After puppet 3, the `deprecation()` function does "warn once" functionality where the developer can limit the amount of messages, and configuration settings for the user to suppress the messages. This is what we'll be using going forward from now, together with the `validate_legacy()` function to step up to data types.

Long-term my goal is that any "last" release of a module in a major series (like the NTP v5.0.0 above) will provide a configuration that a) does not cause deprecation warnings and b) will work unmodified in the major+1 version (like the NTP v6.0.0 release). This should avoid the pain we had with e.g. apt, allow folks to discover the changes they need to make to their config, and update on their own pace.

**Comment by nibalizer** [comment]
@Cinderhaze @hlindberg I don't think we need the deprecation warnings. I get warnings from software all the time that I can do nothing about. Who is this deprecation message for? Someone who is running puppet3 but plugged in enough to the outside world to update to latest of a voxpupuli module? That person should already know that puppet3 is EOL and doesn't need us warning them every time they run puppet.

It is not a module's job to scold you for running an old puppet, I think.

**Comment by nibalizer** [comment]
@DavidS exactly.

* Create a branch or tag at the last functional puppet3 version
* merge puppet 4 code
* drop support for puppet 3 in metadata.json. 
* bump major version
* release 

That can happen at a different time for every module. Or someone can go wild and do it to all the modules in the span of a couple weeks. But I think doing the other 4 steps without having puppet 4 code to merge in is just busywork.

**Comment by rnelson0** [comment]
FWIW I read "We will add a warning" as adding a note to the readme in a published version. I definitely do not like the idea of a warning function adding output to runs.

**Comment by roidelapluie** [comment]
@DavidS What we do with puppet-corosync is we have a LTS version we will support until Puppet 3 vox pupuli depreciation, and newer versions which use puppet 4 features

**Comment by DavidS** [comment]
@roidelapluie technically the last puppet3 compatible ntp version is commercially supported by us, and I would expect to do hotfix releases for security issues, and other critical breakage, but e.g. no new platforms (puppet 3 wouldn't support them anyways), or new features (backporting is rewriting).

**Comment by nibalizer** [comment]
https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/ I ended up writing that and @bbriggs merged it. 

In hindsight, we should have put a nice 'need decision by X' on this so that we'd have our plan in place and people could plan around it.
