### ISSUE TITLE
Vox Pupuli Heroku Account

### ISSUE THREAD

**Issue by petems** [voxpupuli/plumbing#24]
A Heroku account could prove useful, it's a nice easy way of deploying apps quickly to the :cloud: 

The plumbing that comes with that: Login, auto-deploy from Travis/Github etc.

Currently used Heroku apps:

https://github.com/voxpupuli/open-prs

Which is currently hosted on my account, but that means it's a SPOF :cry:

**Comment by igalic** [comment]
@petems do you have access to the credentials store?
Do you have a trustworthy gpg key? :P

**Comment by petems** [comment]
I dont think I do

When you say trustworthy....

**Comment by dhoppe** [comment]
@petems I am not familiar with Heroku and it's sleep mechanism. Do you use the Free or Hobby type? If the Free type is sufficient @bastelfreak should be able to create an account and store the credentials.

**Comment by ekohl** [comment]
Is this still relevant or shall we close it?
