### ISSUE TITLE
Vox Pupuli Avatar

### ISSUE THREAD

**Issue by ShellyCoen** [voxpupuli/plumbing#27]
![img_3658](https://cloud.githubusercontent.com/assets/8882676/14403391/df79e432-fe54-11e5-9b76-7b7cc1f126c3.JPG)
![img_3659](https://cloud.githubusercontent.com/assets/8882676/14403392/e2f82fd8-fe54-11e5-9704-2194d72417a4.JPG)
![img_3678](https://cloud.githubusercontent.com/assets/8882676/14403488/0cc4236e-fe58-11e5-9c5e-3e1438be9f1d.JPG)

new 8bit voxes -

![voxy](https://cloud.githubusercontent.com/assets/8882676/14509255/a6c901de-01cb-11e6-9a5f-dd9012c660f7.png)
![vox8bit](https://cloud.githubusercontent.com/assets/8882676/14509254/a6c7d0e8-01cb-11e6-94ef-f3951987a2ee.png)

Choice of Pictures with the Vox Pupuli Mascot

**Comment by juniorsysadmin** [comment]
2nd one for avatar, 3rd one for top banner thing on the homepage

**Comment by rnelson0** [comment]
I like the 3rd for both.

**Comment by nibalizer** [comment]
2nd one for avatar, 3rd one for top banner thing on the homepage

**Comment by bastelfreak** [comment]
2nd one for avatar, 3rd one for top banner thing on the homepage

**Comment by ahpook** [comment]
Fantastic work! 3rd is my fav.

**Comment by jyaworski** [comment]
2nd one for avatar, 3rd one for top banner thing on the homepage

**Comment by danzilio** [comment]
I'd love to see this drawn as a logo. Maybe some kind of pixel art? The finger puppet makes a great mascot but I'd love to see a logo of it too...

**Comment by DKhalil** [comment]
3rd for both!

**Comment by ShellyCoen** [comment]
@danzilio suggested pixel art, I gave an 8bit vox puppet a go! Possibly this as avatar? Just to confuse matters :) 


![vox8bit](https://cloud.githubusercontent.com/assets/8882676/14508347/49be5556-01c7-11e6-8ab8-d2a15bb81bcc.png)

**Comment by danzilio** [comment]
i love this

**Comment by ShellyCoen** [comment]
I attempted to do shading and I dunno about it, but @igalic said to also share it!
![voxy](https://cloud.githubusercontent.com/assets/8882676/14509230/88937b36-01cb-11e6-84c3-ebdf488af8b2.png)

**Comment by rnelson0** [comment]
This gets my immediate vote as an avatar. I like the original shading
slightly more but either is great!
>
>

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by igalic** [comment]
update: i've made the shady fox avatar our new (gr)avatar.
(on the forge and on github) - THANK YOU SO MUCH @ShellyCoen!

the banner, or, well, the website in general, still needs some :heart:

**Comment by ShellyCoen** [comment]
<3 Glad to be of help!

**Comment by igalic** [comment]
![8bit-vox](https://cloud.githubusercontent.com/assets/497249/14590314/714f4bb0-04f7-11e6-8067-fc21e1684c94.png) btw, here's the 555×555px version i used for gravatar & github

**Comment by igalic** [comment]
i'm going to close this issue now as complete success :tada:
