### ISSUE TITLE
  setup a module-sync for puppet community

### ISSUE THREAD

**Issue by igalic** [voxpupuli/plumbing#3]
we should probably offer (our own?) [module sync](https://github.com/puppetlabs/modulesync), to keep puppet-community module's up-to-date with the current recommended technology.

@nibalizer suggested: Here is some less than optimal scripting around the secrets:

https://github.com/puppet-community/plumbing/blob/travis/share/travis_secrets and puppet-community/plumbing#1

(migrating this issue from https://github.com/puppet-community/puppet-community.github.io/issues/5)

**Comment by nibalizer** [comment]
I think this might actually be a bit premature. Let me explain:

Right now we don't really know what we've got. We've got individual contributors, owners, collaborators, and different modules from different people. I think there is value to letting the various files that modulesync would manage 'float' for a while, maybe 6 weeks or so.

1) I think we don't really know what the dotfiles should look like yet, letting each module quickly set up the files it wants to is the best way to explore the most avenues.

2) I worry that having a 'if you join puppet-community you get these dotfiles' policy or even suggestion might put a bad taste in some people's mouths. I know the people I've talked to have expressed that having control over their own modules is a hard requirement for going to puppet-community.

3) There are a few administrative tasks we need to provide from an infrastructure perspective. pr #1 on this repo provides some minimal infrastructure to collect the 'secure' line needed in travis.yaml for puppet blacksmith to publish to the forge under the 'puppet' user. The idea is someone on the short list of having the password updates the big list of secure lines, then module owners/authors can copy paste into their own module if and when they want to. There are probably other things we need to provide.


I absolutely think we should eventually offer a modulesync configs repo that modules can slave against. That is the best way to keep as igalic said 'up to date with current best technology'. I just think we should hold off on getting super prescriptive. I'm happy to guniea pig the puppetboard module if someone creates a modulesync configs repo.

**Comment by liamjbennett** [comment]
I have to agree about holding off on the modulesync. Having used it for the opentable modules I know we made a lot of changes to our own configuration so I expect people to be very opinionated about the subject.

Having said that, it is possible to have a module's ```.sync.yml``` file exclude the files that you don't want module sync to manage which gives author an opt-out if they have specific changes they want to make or they want to test some new change.

I think the combination of opt-in to a standard modulesync config with the option of opt-out specific files later provides the best flexibility.

**Comment by nibalizer** [comment]
Ya I think its time.

**Comment by igalic** [comment]
let's get going. what do we need?

**Comment by nibalizer** [comment]
A repo to hold the modulesync configs. Example good configs. Some scripts in this repo maybe to kick the whole thing off?

**Comment by igalic** [comment]
step one https://github.com/puppet-community/modulesync_config

**Comment by nibalizer** [comment]
We've been modulesyncing pretty heavily
