### ISSUE TITLE
Add page explaining about no 1.8.7 support

### ISSUE THREAD

**Issue by petems** [voxpupuli/plumbing#36]
There's been a few PR's re-adding or reverting changes that removed 1.8.7 support (ie. hashes in Puppet providers/types). These changes are normally the result of Rubocop changes.

A page on https://voxpupuli.org/ explaining 1.8.7 with something:
- Why support has been dropped, emphasising that 1.8.7 has long been EOL and we don't have the resources (or really, the patience) to support a very dead version of Ruby
- How to get upgraded Ruby packages for LTS distros, such as Software Collections for proper packages or a tool like Rbenv to install particular versions.
- Recommendation to upgrade to Puppet 4 so you get the AIO package with the puppet vendored Ruby
- Workarounds if people still require 1.8.7 support in an emergency (fork repos etc.)

With something like this it gives us an easy copy-pasteable `Closed, won't fix` message for 1.8.7 issues in modules

https://github.com/voxpupuli/puppet-archive/pull/156
https://github.com/voxpupuli/puppet-iis/pull/111
https://github.com/voxpupuli/puppet-mcollective/pull/300
https://github.com/voxpupuli/puppet-mcollective/issues/297
https://github.com/voxpupuli/puppet-nodejs/issues/217
https://github.com/voxpupuli/puppet-jira/issues/136

**Comment by igalic** [comment]
Do it so, :one:

**Comment by petems** [comment]
OK, I've got a rough draft up. You think this should be a blog post or as some sort of more permanant page?

https://www.softwarecollections.org/en/

**Comment by igalic** [comment]
like, voxpupuli.org/blog/ ?

**Comment by jyaworski** [comment]
Can we easily use softwarecollections with Puppet? Does it have to be installed by gem then?

**Comment by juniorsysadmin** [comment]
I don't feel that including softwarecollections is a good recommendation, given the executable is named ruby22 (to avoid any interference with the system Ruby) and also given the fact that your only choice is Ruby 2.2, not 2.3, or 2.1 (if you are attempting to test against the current bundled Ruby that comes with Puppet 4)

**Comment by petems** [comment]
Yeah, looking into it deeper, it seems like a rbenv like approach but with a package. Seems not too up to scratch with what we want...

**Comment by petems** [comment]
https://www.brightbox.com/docs/ruby/ubuntu/

**Comment by rkhatibi** [comment]
One answer you can give users is to run the master on a new version of their distro. Since most of the Ruby heavy lifting runs on the master you get Ruby 1.9.3+ and the agent doesn't need to update. 

I've been running 1.8.7/puppet 3.x agents against 1.9.3+/puppet 3 masters for years. Wrote up our overly complicated process here, https://ask.puppet.com/question/16983/performance-improvements-without-updating-to-puppet-server/

However with SCL it's just a matter of installing the Puppet and supporting gems into SCL and pointing Passenger at the right Ruby path rather than the rvm/rbenv dance.

**Comment by rnelson0** [comment]
We are seeing not just puppet losing support for 1.8.7, but also a number of gems that puppet and its tooling rely on leaving behind 1.8.7 and even 1.9.3. Perhaps we should rethink directing people on how to manage 1.8.7 and encourage them to move to 2.x, lest we have to revisit the instructions every times some gem like `json_pure` decides to require a higher version of Ruby than its previous version did.

**Comment by igalic** [comment]
i absolutely agree. given that almost all of our modules support puppet4, and some *only* support 4, that should also be an angle.

**Comment by juniorsysadmin** [comment]
Not much demand for this now. Closing.
