### ISSUE TITLE
Fix broken puppet-lint-releases (missing rubygems.org key)

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/plumbing#41]
We've a few gems that got migrated into our namespace. We currently can't deploy them because we don't have a rubygems key in their travis config (or they don't even have a travis config)

---

https://github.com/voxpupuli/puppet-lint-reference_on_declaration_outside_of_class-check comes from @tuxmea, it currently has no travis config

---

https://github.com/voxpupuli/puppet-lint-resource_reference_syntax comes from @tuxmea too, also has no travis file.

---

https://github.com/voxpupuli/puppet-lint-appends-check comes from @glarizza, has a travis file but no rubygems key

**Comment by bastelfreak** [comment]
```
22:12:37     nibalizer | i think rubygems is 'smart' so we can just have whomever add the voxpupuli user as authorized in rubygems to deploy that
```

we can try to add a key from our namespace to any of the repos and test

**Comment by rnelson0** [comment]
Of those three, puppet-lint-appends-check [is actually used](https://github.com/search?utf8=%E2%9C%93&q=puppet-lint-appends-check&type=Code&ref=searchresults). That should be our focus on fixing first. The other two are not used in publicly searchable github repositories which limits the impact significantly.

**Comment by tuxmea** [comment]
puppet-lint-resource_reference_syntax is also used in garethr module skeleton.

I added voxpupili user as owner to both of my gems
- puppet-lint-resource_reference_syntax
- puppet-lint-reference_on_declaration_outside_of_class-check

And I did a PR for both covering the missing .travis.yml file:
https://github.com/voxpupuli/puppet-lint-reference_on_declaration_outside_of_class-check/pull/3
https://github.com/voxpupuli/puppet-lint-resource_reference_syntax/pull/8

**Comment by nibalizer** [comment]
awesome

**Comment by nibalizer** [comment]
I'll spin up the automation around voxpupuli-rubygems-secrets tonight

**Comment by tuxmea** [comment]
I am unsure whether the key is set on per user or per gem basis��

**Comment by nibalizer** [comment]
It per repository, because the key is encrypted for travis, by travis.

**Comment by igalic** [comment]
@nibalizer any progress here?

**Comment by ekohl** [comment]
Given its age I'm closing this.
