### ISSUE TITLE
Only support Puppet 3.8 latest

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/plumbing#49]
Our current default testing matrix tests against Puppet 3 and 4 latest only.
Make this a policy on our website somewhere, and adjust the metadata.json for all modules accordingly.

**Comment by juniorsysadmin** [comment]
As seen in the 'Dark Days of Voxpupuli Issue resolution' episode, getting to the bottom of the cause of https://github.com/voxpupuli/puppet-nodejs/issues/149 took forever and still causes flashbacks for those involved.

**Comment by bastelfreak** [comment]
+1 for this. There should not be any big issues with moving from 3.X to latest 3.8 (or even AIO packages). Puppetlabs does a great job in packaging latest 3.8 for many distributions, there weren't many huge changes. Also Puppet3 is EOL end of 2016.

**Comment by juniorsysadmin** [comment]
I'm gonna bump the version in the metadata of all the modules, then close this

**Comment by juniorsysadmin** [comment]
Pull Requests have now been done for this
