### ISSUE TITLE
Test against earlier 3.x versions of Puppet for modules which claim to support them

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/plumbing#50]
Our current default testing matrix includes Puppet 3 latest, not earlier versions. If a module claims to support Puppet 3.5, 3.6 or 3.7 we should add these versions to their Travis file.

Or make it official that we do not support earlier Puppet versions (see #49 )

**Comment by juniorsysadmin** [comment]
STRICT_VARIABLES got introduced in 3.5

**Comment by bastelfreak** [comment]
as noted in #49, I'm against testing multiple versions of puppet3

**Comment by alexjfisher** [comment]
I'd be for testing latest puppet 3 *and* earliest that we claim support for, but not all versions in between.  The metadata.json should reflect reality.  If someone is willing to create PRs to keep a module working with say puppet 3.4, then I don't think we should actively be against this (unless the fix is really hacky).

**Comment by juniorsysadmin** [comment]
Given Puppet 3 EOL is coming up quickly, is there still value in doing this?

**Comment by alexjfisher** [comment]
Probably not.  When we do drop testing against puppet 3, there'd probably be some value in testing at least one earlier version of puppet 4 as well as the latest.  Earlier this week, I caught a stdlib regression where the changes they'd made only worked with puppet >=4.6

**Comment by dhoppe** [comment]
Since we test against the latest Puppet 3 release and it is going to be EOL soon, we should drop the support for previous releases. Anything else would make the matrix to complex or stress Travis CI unnecessary.

**Comment by juniorsysadmin** [comment]
Closing due to no action and impending EOL dates. What a slacker.
