### ISSUE TITLE
Add support for Ubuntu 16.04

### ISSUE THREAD

**Issue by dhoppe** [voxpupuli/plumbing#87]
Most of the modules does not have support for Ubuntu 16.04. We should check if everything works as expected. 

Do not forget to modify the metadata.json.

**Comment by wyardley** [comment]
I've done some updates with nginx recently 
https://github.com/voxpupuli/puppet-nginx/pull/951

I did have to temporarily do this switch to get acceptance tests working w/ 16
https://github.com/voxpupuli/puppet-nginx/pull/954

**Comment by ekohl** [comment]
Closing this since it's not that relevant anymore. I think most have been done by now.
