### ISSUE TITLE
Enhance RSpec tests

### ISSUE THREAD

**Issue by dhoppe** [voxpupuli/plumbing#88]
We should use the results of Coveralls to get the RSpec tests fully covered. 

Maybe we should check if the overrides at spec_helper.rb are still necessary.

**Comment by ekohl** [comment]
Is this still relevant?

**Comment by alexjfisher** [comment]
In modules, cove coverage is unfortunately only available for types/providers.  It doesn't work with functions, (and isn't applicable to rspec-puppet tests).
Last time I looked into it, I think replacing coveralls with codecov looked preferable anyway.
